include(CheckTypeSize)
include(CheckCSourceCompiles)

set(RBP_REGISTERED_CURVES "")
set(RBP_REGISTERED_TAGS "")

function(rbp_register_curve name)
    cmake_parse_arguments(PARSE_ARGV 1 ARG "" "TAG;PRESET" "")
    if (NOT name MATCHES "^[a-z_][a-z0-9_]*$")
        message(FATAL_ERROR "Curve name '${name}' must be a lowercase C identifier, because it becomes a RELIC label.")
    endif ()
    if (NOT ARG_TAG OR NOT ARG_PRESET)
        message(FATAL_ERROR "Curve '${name}' needs both TAG and PRESET.")
    endif ()
    if (name IN_LIST RBP_REGISTERED_CURVES OR ARG_TAG IN_LIST RBP_REGISTERED_TAGS)
        message(FATAL_ERROR "Curve '${name}' or tag '${ARG_TAG}' is registered twice.")
    endif ()
    set(RBP_REGISTERED_CURVES ${RBP_REGISTERED_CURVES} ${name} PARENT_SCOPE)
    set(RBP_REGISTERED_TAGS ${RBP_REGISTERED_TAGS} ${ARG_TAG} PARENT_SCOPE)
    set(RBP_CURVE_${name}_TAG ${ARG_TAG} PARENT_SCOPE)
    set(RBP_CURVE_${name}_PRESET ${ARG_PRESET} PARENT_SCOPE)
endfunction()

rbp_register_curve(bls12_381 TAG BLS12_381 PRESET gmp-pbc-bls381)
rbp_register_curve(ss1536 TAG SS1536 PRESET gmp-pbc-ss1536)
rbp_register_curve(bn254 TAG BN254 PRESET gmp-pbc-bn254)

function(rbp_measure_curve name)
    set(CMAKE_REQUIRED_INCLUDES ${ARGN})
    set(CMAKE_EXTRA_INCLUDE_FILES relic.h)
    set(CMAKE_REQUIRED_QUIET ON)
    if (RBP_RELIC_${name}_RECONFIGURED)
        unset(RBP_${name}_IS_SYMMETRIC CACHE)
    endif ()
    foreach (kind IN ITEMS zp:bn_st g1:g1_t g2:g2_t gt:gt_t)
        string(REPLACE ":" ";" pair ${kind})
        list(GET pair 0 key)
        list(GET pair 1 type)
        if (RBP_RELIC_${name}_RECONFIGURED)
            unset(RBP_${name}_${key}_SIZE CACHE)
            unset(HAVE_RBP_${name}_${key}_SIZE CACHE)
        endif ()
        check_type_size(${type} RBP_${name}_${key}_SIZE LANGUAGE C)
        if (NOT RBP_${name}_${key}_SIZE)
            message(FATAL_ERROR "Could not measure ${type} for curve '${name}' from ${ARGN}.")
        endif ()
        set(RBP_${name}_${key}_SIZE ${RBP_${name}_${key}_SIZE} PARENT_SCOPE)
    endforeach ()
    check_c_source_compiles("
        #include <relic.h>
        #if !pc_map_is_type1()
        #error asymmetric
        #endif
        int main(){ return 0; }" RBP_${name}_IS_SYMMETRIC)
    set(RBP_${name}_IS_SYMMETRIC ${RBP_${name}_IS_SYMMETRIC} PARENT_SCOPE)
endfunction()
