name: LibRBP CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  asym_build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libgmp-dev libmpfr-dev libssl-dev cmake lcov

      - name: Checkout RELIC
        uses: actions/checkout@v4
        with:
          repository: relic-toolkit/relic
          path: relic

      - name: Install RELIC asymmetric curve
        run: |
          mkdir relic/build
          cd relic/build
          ../preset/gmp-pbc-bls381.sh ..
          sudo make
          sudo make install

      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Configure CMake (coverage flags)
        run: cmake -B build -S . -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DENABLE_CODE_COVERAGE=ON

      - name: Build
        run: cmake --build build --parallel

      - name: Install
        run: cmake --install build --prefix ${{ github.workspace }}/install

      - name: Run tests
        run: ctest --test-dir build --output-on-failure

      - name: Capture coverage (lcov)
        run: |
          lcov --directory build --capture --output-file coverage.info
          # Remove system and test files from the report
          lcov --remove coverage.info '/usr/*' '*/tests/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.info
          flags: unittests
          fail_ci_if_error: true


  sym_build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential libgmp-dev libmpfr-dev libssl-dev cmake

      - name: Checkout RELIC
        uses: actions/checkout@v4
        with:
          repository: relic-toolkit/relic
          path: relic

      - name: Install RELIC symmetric curve
        run: |
          mkdir relic/build
          cd relic/build
          ../preset/gmp-pbc-ss1536.sh ..
          sudo make
          sudo make install

      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Build and install project
        run: |
          mkdir build
          cd build
          cmake ..
          sudo make
          sudo make install

      - name: Run tests
        run: |
          cd build
          ctest

      - name: Build demo
        run: |
          mkdir demo/build
          cd demo/build
          cmake ..
          sudo make

      - name: Run demo
        run: |
          cd demo/build
          ./demo
